.gitignore, Makefile, builder/bazel-build-filter.sh, cloudbuild.yaml, pkg/cmd/build/build.go
allows user to select build dir (defaults to .)
=> build-dir option for build cmd

builder/bazel-build-filter.sh, docs/content/tutorial_code/getting_started_1.md, pkg/cmd/build/build.go
fixes a bug (regression?) in build command
=> fix build, docs typos

LICENSE.txt
=> Add Apache2 license from https://www.apache.org/licenses/LICENSE-2.0.txt

changelog/v0.0.16/cache-race.yaml, docs/content/reference/cli/wasme_deploy_istio.md, docs/content/reference/cli/wasme_undeploy_istio.md, go.mod, operator/generate.go, operator/install/wasme-default.yaml, operator/install/wasme/templates/deployment.yaml, operator/install/wasme/templates/rbac.yaml, pkg/cache/deploy.go, pkg/cache/deploy_test.go, pkg/cache/notifying_cache.go, pkg/cache/watch.go, pkg/cmd/cache/cache.go, pkg/cmd/deploy/options.go, pkg/cmd/operator/operator.go, pkg/deploy/gloo/gloo_provider.go, pkg/deploy/istio/istio_provider.go, pkg/deploy/istio/istio_provider_test.go, pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/util/retry.go, test/e2e/operator/happy_path_e2e_test.go, test/utils.go
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/64
=> Fix cache race status

changelog/v0.0.17/cache-race.yaml, docs/content/installation/_index.md, docs/content/tutorial_code/getting_started/_index.md, pkg/cache/notifying_cache.go, pkg/cache/watch.go, pkg/cmd/list/list.go
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/87
=> Fix empty list error

changelog/v0.0.18/fix-istio-cpp-abiversion.yaml, pkg/cmd/initialize/initialize.go
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/90
=> fix init interactive mode

changelog/v0.0.19/cache-race.yaml, pkg/cmd/list/list.go
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/87
=> fix list when storageDir is empty

.github/workflows/release.yaml
See https://github.com/solo-io/wasme/runs/981348603?check_suite_focus=true
=> Install build dependencies before creating operator-gen image

.github/workflows/release.yaml
Fixes https://github.com/solo-io/wasme/runs/981506667?check_suite_focus=true
=> Add Github token so build can release assets

sdks/README.md, spec/README.md, tools/README.md
Creating new readme docs for some of the sub-directories and adding some more detail to the OCI spec.
=> README.md updates 

README.md, sdks/README.md, spec/README.md
Minor edits to README files for consistency and clarity.
=> minor edits

spec/README.md
use the module word so this spec is not solo specific
cc @mandarjog @ilackarms
=> use module wording

.github/workflows/release.yaml
Please include a summary of the changes.
This bug fixes ... \ This new feature can be used to ...
Users ran into this bug doing ... \ Users needed this feature to ...
=> working dir for release

tools/wasme/changelog/v0.0.27.1/fixscripts.yaml, tools/wasme/cli/Makefile, tools/wasme/cli/ci/upload_github_release_assets.go, tools/wasme/cli/docs/Makefile
Please include a summary of the changes.
This bug fixes ... \ This new feature can be used to ...
Users ran into this bug doing ... \ Users needed this feature to ...
=> fix gh binaries

tools/wasme/changelog/v0.0.27-patch1/fixscripts.yaml
changelog only so we can release with correct semver
=> fix semver

tools/wasme/changelog/v0.0.28/cache.yaml, tools/wasme/cli/operator/install/wasme/templates/deployment.yaml, tools/wasme/cli/pkg/cache/notifying_cache.go, tools/wasme/cli/pkg/deploy/istio/istio_provider.go
count events based of hostname
=> Fix cache overshoot

.github/workflows/pull_request.yaml, tools/wasme/changelog/v0.0.29/cache.yaml, tools/wasme/cli/ci/check-code-and-docs-gen.sh
Add a codegen check as part of CI on every PR. Uses the same approach we use in Gloo.
This should prevent master's generated files from falling out of sync with the source files.
=> Codegen ci check

tools/README.md, tools/wasme/changelog/v0.0.12/operator-implementation.yaml, tools/wasme/changelog/v0.0.13/fix-deploy-local.yaml, tools/wasme/changelog/v0.0.13/gloo-e2e.yaml, tools/wasme/changelog/v0.0.13/operator-implementation.yaml, tools/wasme/changelog/v0.0.14/operator-implementation.yaml, tools/wasme/changelog/v0.0.16/cache-race.yaml, tools/wasme/changelog/v0.0.17/cache-race.yaml, tools/wasme/changelog/v0.0.18/fix-istio-cpp-abiversion.yaml, tools/wasme/changelog/v0.0.19/cache-race.yaml, tools/wasme/changelog/v0.0.20/command-line-credentials.yaml, tools/wasme/changelog/v0.0.21/add-istio-1.6-support.yaml, tools/wasme/changelog/v0.0.21/fix-bookinfo-url, tools/wasme/changelog/v0.0.21/fix-typo-cahced.yaml, tools/wasme/changelog/v0.0.21/gloo-1.5.yaml, tools/wasme/changelog/v0.0.21/gloo-and-istio-support.yaml, tools/wasme/changelog/v0.0.21/use-recent-envoy.yaml, tools/wasme/changelog/v0.0.26/version-fix.yaml, tools/wasme/cli/docs/content/tutorial_code/build_tutorials/building_assemblyscript_filters.md, tools/wasme/cli/docs/content/tutorial_code/build_tutorials/building_cpp_filters.md, tools/wasme/cli/docs/content/tutorial_code/getting_started/_index.md
I found the old links in this repo, so I updated them.
Related PR: https://github.com/solo-io/wasm/pull/181
=> Update docs links to reflect restructured repo

tools/wasme/changelog/v0.0.32/istio-as-1-7.yaml, tools/wasme/cli/builder/Dockerfile, tools/wasme/pkg/cache/cache.go, tools/wasme/pkg/cache/cache_state.go, tools/wasme/pkg/defaults/defaults.go, tools/wasme/pkg/util/proto.go
this expands the Wasm Cache to allow just-in-time pulling of images based on ref. also adds logging and a small refactor to the wasm cache
=> support lazy-loading cache

tools/wasme/cli/docs/content/tutorial_code/wasme_operator.md
*Docs only update*
Update the wasme Istio operator docs to reflect the changes in the `config` field of the proto
Clears up the config issue reported in https://github.com/solo-io/wasm/issues/236
=> Update Operator docs to reflect latest Istio config

tools/wasme/cli/docs/content/tutorial_code/build_tutorials/building_assemblyscript_filters.md, tools/wasme/cli/docs/content/tutorial_code/build_tutorials/building_cpp_filters.md, tools/wasme/cli/docs/content/tutorial_code/deploy_tutorials/deploying_with_istio.md, tools/wasme/cli/docs/content/tutorial_code/getting_started/_index.md
Please include a summary of the changes.
This bug fixes ... \ This new feature can be used to ...
Users ran into this bug doing ... \ Users needed this feature to ...
=> feat:update the solo.io doc

.github/workflows/pull_request.yaml, .github/workflows/release.yaml, tools/wasme/changelog/v0.0.34/upgrade-go-1.15.yaml, tools/wasme/cli/example/tinygo/go.mod, tools/wasme/cli/example/tinygo/go.sum, tools/wasme/cli/go.mod, tools/wasme/cli/go.sum, tools/wasme/cli/pkg/auth/login.go, tools/wasme/cli/pkg/cmd/cmd.go, tools/wasme/cli/pkg/cmd/list/list.go, tools/wasme/cli/pkg/cmd/login/login.go, tools/wasme/cli/pkg/defaults/defaults.go, tools/wasme/pkg/cache/cache.go, tools/wasme/pkg/defaults/defaults.go, tools/wasme/pkg/go.mod, tools/wasme/pkg/store/store.go
Please include a summary of the changes.
upgrade go version and solve unreasonable package dependencies
This bug fixes ... \ This new feature can be used to ...
Users ran into this bug doing ... \ Users needed this feature to ...
=> feat:upgrade go version and solve unreasonable package dependencies
