solo-io/wasm

changelog/v0.0.12/rust-examples.yaml, example/rust/README.md, example/rust/src/host.rs
Add some more details to how to build wasm plugins via rust and cargo. Fixes some of the proxy function signatures to reflect what envoy expects. I used [this list](https://github.com/envoyproxy/envoy-wasm/blob/master/api/wasm/cpp/proxy_wasm_externs.h) to compare the signatures.
=> Fix rust examples

changelog/v0.0.20/command-line-credentials.yaml, pkg/cmd/cache/cache.go, pkg/defaults/defaults.go
This is the first step to resolve #101
The wasme cache will now use credentials given to its command line.
Separately, we will have to look at a way to pick the [FilterDeployment pullSecret](https://github.com/solo-io/wasme/blob/master/operator/api/wasme/v1/filter_deployment.proto#L58) dynamically.
For the time being, people who want to try this with the operator need a few extra steps.
```bash
kubectl create secret generic image-registry --dry-run --output=yaml \
--from-literal=username=$GCR_USER \
--from-literal=password="$GCR_PASSWORD" -n wasme | kubectl apply -f -
```
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
labels:
app: wasme-cache
name: wasme-cache
namespace: wasme
spec:
selector:
matchLabels:
app: wasme-cache
template:
metadata:
labels:
app: wasme-cache
annotations: …
```
=> Let wasme cache use OCI registry credentials

docs/content/reference/cli/wasme_deploy_istio.md
I found this closed issue when trying to see why passing a deployment name wasn't working.
https://github.com/solo-io/wasme/issues/93
Hoping to fix the docs for the next person that might see them.
=> Update wasme deploy docs

changelog/v0.0.21/fix-bookinfo-url, docs/content/tutorial_code/wasme_operator.md
Previously, the kubectl apply pointed at GitHub's html page rather than at the raw file. This gave:
```
error: error parsing https://github.com/solo-io/wasme/blob/master/test/e2e/operator/bookinfo.yaml: error converting YAML to JSON: yaml: line 116: mapping values are not allowed in this context
```
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/122
=> Fix Bookinfo URL

changelog/v0.0.21/add-noop-cloudbuild.yaml, cloudbuild.yaml
When this file was removed, bulldozer bot broke. We should
remove the cloudbuild dependency from bulldozer bot as a long
term solution, but to restore functionality this file serves as
a workaround.
=> Added noop cloud build file to pass CI

changelog/v0.0.21/fix-bulldozer-bot.yaml, cloudbuild.yaml
Permissions issue was fixed, bulldozer does not need a valid cloudbuild config to run.
=> Fix bulldozer

.github/workflows/pull_request.yaml, changelog/v0.0.21/add-istio-1.6-support.yaml, docs/content/reference/cli/wasme_deploy_istio.md, docs/content/reference/cli/wasme_init.md, pkg/abi/version.go, pkg/abi/version_test.go, pkg/cmd/deploy/deploy.go, pkg/cmd/initialize/initialize.go, pkg/deploy/filter/envoy_filter.go, pkg/deploy/istio/istio_provider.go
This PR will allow initializing wasme filters for & deploying them to Istio 1.6.
As Istio 1.6 uses an envoy ABI which is backwards compatible with Istio 1.5, this means any wasme images targeting Istio 1.5 will work with Istio 1.6 without any changes necessary.
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/126
=> Support Istio 1.6

.github/workflows/pull_request.yaml, .github/workflows/release.yaml, changelog/v0.0.22/wasm-build.yaml, test/e2e/operator/happy_path_e2e_test.go
After we write the CRD and the wasm image cache is hydrated, write it again now that the image is in the cache. Seems to help a lot with the current cache race condition.
Separately, move the Github action workflow controlling releases into its own action.
=> Add filter load step before testing real filter + refactor release flow

.github/workflows/release.yaml
To fix https://github.com/solo-io/wasme/runs/981638637?check_suite_focus=true
=> Add hugo so docs can be released as part of CI/CD

changelog/v0.0.26/version-fix.yaml, docs/Makefile, pkg/version/version.go
This was causing the version to always be "dev", which caused the wrong version of Istio operator image to be deployed.
BOT NOTES: 
resolves https://github.com/solo-io/wasme/issues/158
=> Fix a bug in version linking

Makefile, changelog/v0.0.27/docs-publish.yaml, docs/Makefile
For the 0.0.26 release the CI/CD process failed to automatically push the latest docs changes. `GCLOUD_PROJECT_ID` wasn't being set correctly, this should fix the CI/CD.
=> Default GCR project at top level and docs level makefile

tools/wasme/changelog/v0.0.27/ignore-version-check.yaml, tools/wasme/cli/pkg/cmd/deploy/options.go, tools/wasme/cli/pkg/deploy/istio/istio_provider.go, tools/wasme/cli/pkg/deploy/istio/istio_provider_test.go, tools/wasme/cli/pkg/operator/operator.go
New flag is `--ignore-version-check`, should help with filter development against new versions of Istio & Gloo.
Implements https://github.com/solo-io/wasm/issues/68
=> Add flag to wasme deploy to allow ignoring ABI version check

sdks/README.md
I've joined @tetrateio this month, and transferred my TinyGo SDK to tetratelabs organization. Thanks!
=> fix URL of TinyGo SDK

tools/wasme/cli/example/rust-istio-1.7/runtime-config.json
Lets `wasme deploy` deploy the rust filter to Istio 1.5/1.6. Currently the filter works, but the `runtime-config.json` doesn't list that version as compatible.
=> Add ABI verison for Istio 1.5/1.6

tools/wasme/changelog/v0.0.30/istio-as-1-7.yaml, tools/wasme/cli/example/assemblyscript/runtime-config.json
In wasme v0.0.29, create an assemblyscript filter targeting Istio 1.7.
The filter itself will work with Istio 1.7, but the example generated by wasme init is missing the version information from the runtime-config.json to allow it to deploy to Istio 1.7.
Fixes https://github.com/solo-io/wasm/issues/216
=> Fix Istio 1.7 / Assemblyscript

tools/wasme/cli/docs/content/tutorial_code/wasme_operator.md
Fixes wasme Operator tutorial: `istio-test` image is missing; long live `assemblyscript-test`.
The old image does not exist.
=> Documentation fix for 'wasme Operator' tutorial

.github/workflows/pull_request.yaml, tools/wasme/changelog/v0.0.31/bump-kind-setup.yaml
GH API has changed and is no longer supported, the new version of the GitHub Action uses the newer, supported API.
=> Bump setup-kind step in CI/CD

tools/wasme/cli/docs/content/tutorial_code/getting_started/_index.md
Quick docs fix to reflect that "namespace": {"create":"true"} is no longer required when installing via `glooctl`.
Fixes https://github.com/solo-io/wasm/issues/62
=> Update docs to reflect namespace create no longer required

tools/wasme/cli/pkg/deploy/istio/istio_provider.go, tools/wasme/cli/pkg/deploy/istio/istio_provider_test.go
This bug fixe restore istio annotation issues
=> Fix restore istio annotation bug

tools/wasme/cli/docs/content/tutorial_code/deploy_tutorials/deploying_with_gloo.md, tools/wasme/cli/docs/content/tutorial_code/getting_started/_index.md
Change Gloo install references to indicate enterprise edition is required for WASM.
Closes solo-io/gloo#4135
=> Change Gloo install references to indicate enterprise edition is required

.github/workflows/pull_request.yaml, tools/wasme/pkg/defaults/defaults.go
Update tests to use released version of Istio 1.8.x rather than the pre-release alpha version.
Also pins helm to 3.2 for codegen, to be consistent with the other tests.
=> Update e2e tests for Istio 1.8.x

spec/README-compat.md, spec/README.md, spec/spec-compat.md, spec/spec.md
**Description**
Following the discussion (led by @dgn) in the Istio Wasm-SIG, this PR added a variant of Wasm image spec for storing Wasm binaries as standard container images. 
Notably this new spec leverages the existing standard layers with either one of
- `application/vnd.oci.image.layer.v1.tar+gzip` or 
- `application/vnd.docker.image.rootfs.diff.tar.gzip`
media type, not based on the OCI Artifact Spec. This allows users to use standard CLI tools in container ecosystem (such as `docker`, `podman`, `buildah`, etc.) and push to any standard registries without requiring support for arbitrary mediaType (including the one used before).
See #208 and [a meeting note by @dgn](https://docs.google.com/document/d/1Uf-3RPFRyNl6ExYUeZERlB9Y8kyxZFaB6NbDZyguXwI/edit) for the background, and …
=> Add a variant of Wasm image spec based on standard media types.

.github/workflows/issue_board.yaml, tools/wasme/changelog/v0.0.35/issue-automation.yaml
First PR for this: https://github.com/solo-io/gloo/issues/6305
It's hard to manually test github actions so my plan is to manually verify in this repo before implementing in the other repos.
=> Add github action to add new issues to project board

.github/workflows/issue_board.yaml, tools/wasme/changelog/v0.0.35/gha_secret.yaml
The secret I used in the last iteration does not have permissions to edit issues/update team boards. 
Previous PR: https://github.com/solo-io/wasm/pull/287
=> Update secret for GHA

.github/workflows/issue_board.yaml, tools/wasme/changelog/v0.0.35/gha_secret.yaml, tools/wasme/changelog/v0.0.35/new-token.yaml
The existing personal access token couldn't read the team boards.
=> Use the newly created token for the GHA to add issues to boards
